services:
  - type: web
    name: driversnote-assessment-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: HOST
        value: 0.0.0.0
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: driversnote
      - key: API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: "*"
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 900000
